var GAME_LEVELS = [
  [
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                    xxxxx       ",
    "                          o                                         xx!xx       ",
    "                                                                    xx!xx       ",
    "                          x                                           v         ",
    "                      o       o                                                 ",
    "                                                                                ",
    "                     xxx     xxx                                             o  ",
    "                                                                           xxxxx",
    "                                       o  o  o  o                          xxxxx",
    "    @                                                                      xxxxx",
    "xxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "         x!!!x                                                                  ",
    "         x!!!x                                                                  ",
    "         xxxxx                                                                  ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
  ],
  [
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                     x          x                                             ",
   "                                                                                    x!x        x!x                                            ",
   "                                                                  xxx                v     o    v    o                       xxx              ",
   "                                                   xx      xx    xx!xx                                                      xx!xx             ",
   "                                    o o      xx                  x!!!x                    xxx       xxx                     x!!!x             ",
   "                                                                 xxvxx                                                      xxvxx             ",
   "                                   xxxxx                                            xxx        xxx       xxx                  o               ",
   "                                                                                                                                              ",
   "                                          o o                                                                                x x            o ",
   "                        o                                                                                         xxx        xox            x ",
   "                                         xxxxx                            o    xxxxxxx                                      xx xx          xx ",
   "             xxxx       o       o                                              x     x        o        o                                  xxx ",
   "     @       x  x                                                xxxxx         x     x                           x!!!x                   xxxx ",
   "xxxxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                              x   x                  x     x                                                                                  ",
   "                              x!!!x                  x!!!!!x                                                                                  ",
   "                              x!!!x                  x!!!!!x                                                                                  ",
   "                              xxxxx                  xxxxxxx                                                                                  ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                "
  ],
  [
    "                                                                                                                                                                                                   ",
    "                                                                                                                                                                                                   ",
    "                                                                                                                                                                                                   ",
    "                                                                                                                                                                                                   ",
    "                                                                                                                                                                                                   ",
    "                                                                                                                                                                                                   ",
    "                                                                                                                                                                                                   ",
    "                                                                                                                                                                                                   ",
    "                                                                                                                                                                                                   ",
    "                                                  x o x                                                                                                                                            ",
    "                                                  xxxxx                                                       xxxxxx                   o                                                           ",
    "                                                                                                                                  ss  xx                                                           ",
    "                                                        xx                                                                      o xx                                                               ",
    "                                                                v                                                              xx                                                                  ",
    "                                                           ss                                                                                                                      xxxxxxx         ",
    "                                      v             o xx   xx o                                                                                                                    xx!!!xx         ",
    "                                                  ? o xx   xx o                     xxs oo sxx     ss         ?    ?         o                                oo           oo  o      v           o",
    "                                   xx   xx        o xxxx   xxxx o                   xxxxxxxxxx     xx o       x    x        xx                               xxxx         xxxx x  o       o      ox",
    "                                   xx   xx      o xxxxxx   xxxxxx o                                xxxx o     x  o x      xxxx                               xxxx    o    xxxx x  xx     xx      xx",
    "      @        ssss    xo = ox     xx o xx      xxxxxxxx   xxxxxxxx         ss      o o o o o o    xxxxxx     x  o x    xxxxxx             ssss            ssxxxx   xxx   xxxx x      o          xx",
    "xxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxx  xxx   xxxxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxx          xxxxxxxxxxxx   xxxxxxxxxx!!!xxx!!!xxxx x xxxxxxxxxx xxxxxxx",
    "         x!!!x                                                         x!!!x                                                                       x!!!x                                           ",
    "         x!!!x                                                         x!!!x                                                                       xxxxx                                           ",
    "         xxxxx                                                         xxxxx                                                                                                                       ",
    "                                                                                                                                                                                                   ",
    "                                                                                                                                                                                                   ",
    "                                                                                                                                                                                                   ",
    "                                                                                                                                                                                                   ",
    "                                                                                                                                                                                                   ",
    "                                                                                                                                                                                                   ",
    "                                                                                                                                                               "
  ],
  [
    "                                                                                                                                                                                                                                  ",
    "                                                                                                                                                                                                                                  ",
    "                                                                                                                                                                                                                                  ",
    "                                                                                                                                                                                                    x         x                   ",
    "                                                                                                                                                                                                                                  ",
    "                                                                                                                                                                                                                                  ",
    "                                                                                                                                                                                                                                  ",
    "                                                                                                                                                                                                                                  ",
    "                                                                                                                                                                                                    ?         ?                   ",
    "                                                  x o x                                                                                                                                             x         x                   ",
    "                                                  xxxxx                                   xxx                 xxxxxx                   o                                                            xxxxxxxxxxx                   ",
    "                            o                                                                                                      s  xx                                                                                          ",
    "                           xxx                          xx                          xxx                                         o xxx                                                             xxx         xxx      x x        ",
    "                         oxxxx                                  v                   xvx                                        xx                                                                                      v          ",
    "                        xxxxxx                             ss                                                                                                                      xxxxxxx                                        ",
    "                       xxxxxxx        v             o xx   xx o                            o                                                                                       xx!!!xx      xxx              xxx              ",
    "                        o   o                     ? o xx   xx o                           x?x      oo         ?    ?         o                                oo           oo  o      v                  o                       o",
    "                          o        xx   xx        o xxxx   xxxx o                         xxx      xx s       x    x        xx                               xxxx         xxxx x  o       o                             o       ox",
    "                       xxxxxxx     xx   xx      o xxxxxx   xxxxxx o                                xxxx o     x  o x      xxxx                               xxxx q  o    xxxx x  xx     xx   xxx        o         xxx          xx",
    "      @        ss      xxxxxxx     xx o xx     qxxxxxxxx   xxxxxxxx         ss      o o o o o o    xxxxxxs    x  o x    xxxxxx             ssss            ssxxxx   xxx   xxxx x      o             xq         x        o?      xx",
    "xxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxx  xxx   xxxxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxx          xxxxxxxxxxxx   xxxxxxxxxx!!!xxx!!!xxxx x xxxxxxxxxx         xxxxxxxxxxxx       xxx  xxxxxx",
    "         x!!!x                                                                                                                                     x!!!x                                                                          ",
    "         x!!!x                                                                                                                                     xxxxx                                                                          ",
    "         xxxxx                                                                                                                                                                                                                    ",
    "                                                                                                                                                                                                                                  ",
    "                                                                                                                                                                                                                                  ",
    "                                                                                                                                                                                                                                  ",
    "                                                                                                                                                                                                                                  ",
    "                                                                                                                                                                                                                                  ",
    "                                                                                                                                                                                                                                  ",
    "                                                                                                                                                                                                                                  "
  ],
  [
    "                                                                                                                                                                                                                                                                                                                                                 ",
    "                                                                                                                                                                                                                                                                                                                                                 ",
    "                                                                                         o                                                                                                                                                                                                                                                       ",
    "                                                                                      o     o                                                                                                                                                                                                                                                    ",
    "                                                                                   o           o                                                                                                                                                                                                                                                 ",
    "                                                                              s       o     o    s                                                                                                                                                                                                                                               ",
    "                                                                              xs         o   q  sx                                                                                                                                                                                                                                               ",
    "                                                                              xxxxxxxxxxxxxxxxxxxx                                                                                                                                                                                                                                               ",
    "                                                                           o                     x                                                                                                                                                                                                                                               ",
    "                                                                          xx       xxxxxx        x                                                                                                                                                                                                                                               ",
    "                                                                         o                       x                                                                                                                                                                                                                                               ",
    "                                                                        xx                       x                                                                 x              x                                                                                                                                                              ",
    "                                                                       o                         x   o o                                                           x  o    q   o  x                                                                                                                                                              ",
    "                                                                      xx                         x  xxxxx                                                          x  xxxxxxxxxx  x                                                                                                                                                              ",
    "                                                                     o                           x    v            xxxxx                                       x   x  x    v   x  x                                                                                                                   xxxxxxx                                    ",
    "                                                                   xxx                           x                 v               x                         o     x  xo      ox  x                                                        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                             x  v  x                                    ",
    "                                                                                                                                   xx=             x         x     x  xx      xx  x                           xxxxxx                       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                             x     x                                    ",
    "                                                                                                                                   x               x       o                                                  x                            xxxxxxxxxxxxxxxxxxxxx                                                                                 ",
    "                                                      oo   oo                      oo                                o             x       o     =xx       x                                                  x                                                                                                                    ooq           ",
    "                                                     oxx   xx                                         o             o o                 o     o    x               xxxxxxxxxxxxxxxx                          xxo                oo                                                                                 ooo           xxxxx           ",
    "        s    s             xxxx         o         ssxxxx   xxxx                                                      o                     o             x                oo                                  x     qx        xxxxxx                                                                                           o        o        ",
    "        x  o x             oooo      o     o      xxxxxx   xxxxxx                                   x ? x                                                                                                     xxxxxxxx                     x=                         xxxxxxxxxx                                x      qx     xxxxxxxxxxxx       ",
    "    @   xxxxxx                     x       qx  =xxxxxxxx!!!xxxxxxxx          ss           ss        xxxxx              ?                                                                        x  o  =x  o  qx               ssssss       x        o     o        =xxxxxxxxxxxx         ss   sss                xxxxxxx                         ",
    " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ssss xxxxxx xxx xxx xxxxxxx              xxxxx       xxxxxxxxxx",
    "                                                                                                                                                                                                                                                                                                                                                 ",
    "                                                                                                                                                                                                                                                                                                                                                 ",
    "                                                                                                                                                                                                                                                                                                                                                 ",
    "                                                                                                                                                                                                                                                                                                                                                 ",
    "                                                                                                                                                                                                                                                                                                                                                 ",
    "                                                                                                                                                                                                                                                                                                                                                 "
  ]
];
