var GAME_LEVELS = [
  // [
  //  "                                                                                ",
  //  "                                                                                ",
  //  "                                                                                ",
  //  "                                                                                ",
  //  "                                                                                ",
  //  "                                                                                ",
  //  "                                                                                ",
  //  "                                                                                ",
  //  "                                                                    xxxxx       ",
  //  "                          o                                         xx!xx       ",
  //  "                                                                    xx!xx       ",
  //  "                          x                                           v         ",
  //  "                      o       o                                                 ",
  //  "                                                                                ",
  //  "                     xxx     xxx                                             o  ",
  //  "                                                                           xxxxx",
  //  "                                       o  o  o  o                          xxxxx",
  //  "    @                                                                      xxxxx",
  //  "xxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  //  "         x!!!x                                                                  ",
  //  "         x!!!x                                                                  ",
  //  "         xxxxx                                                                  ",
  //  "                                                                                ",
  //  "                                                                                ",
  //  "                                                                                ",
  //  "                                                                                ",
  // ],
  // [
  //  "                                                                                                                                              ",
  //  "                                                                                                                                              ",
  //  "                                                                                                                                              ",
  //  "                                                                                                                                              ",
  //  "                                                                                     x          x                                             ",
  //  "                                                                                    x!x        x!x                                            ",
  //  "                                                                  xxx                v     o    v    o                       xxx              ",
  //  "                                                   xx      xx    xx!xx                                                      xx!xx             ",
  //  "                                    o o      xx                  x!!!x                    xxx       xxx                     x!!!x             ",
  //  "                                                                 xxvxx                                                      xxvxx             ",
  //  "                                   xxxxx                                            xxx        xxx       xxx                  o               ",
  //  "                                                                                                                                              ",
  //  "                                          o o                                                                                x x            o ",
  //  "                        o                                                                                         xxx        xox            x ",
  //  "                                         xxxxx                            o    xxxxxxx                                      xx xx          xx ",
  //  "             xxxx       o       o                                              x     x        o        o                                  xxx ",
  //  "     @       x  x                                                xxxxx         x     x                           x!!!x                   xxxx ",
  //  "xxxxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  //  "                              x   x                  x     x                                                                                  ",
  //  "                              x!!!x                  x!!!!!x                                                                                  ",
  //  "                              x!!!x                  x!!!!!x                                                                                  ",
  //  "                              xxxxx                  xxxxxxx                                                                                  ",
  //  "                                                                                                                                              ",
  //  "                                                                                                                                              ",
  //  "                                                                                                                                              ",
  //  "                                                                                                                                              ",
  //  "                                                                                                                                              ",
  //  "                                                                                                                                              ",
  //  "                                                                                                                                              ",
  //  "                                                                                                                                              ",
  //  "                                                                                "
  // ],
  [
    "                                                                                                                                                                                       ",
    "                                                                                                                                                                                       ",
    "                                                                                                                                                                                       ",
    "                                                                                                                                                                                       ",
    "                                                                                                                                                                                       ",
    "                                                                                                                                                                                       ",
    "                                                                                                                                                                                       ",
    "                                                                                                                                                                                       ",
    "                                                                                                                                                                                       ",
    "                                                  x o x                                                                                                                                ",
    "                                                  xxxxx                                                       xxxxxx                   o                                               ",
    "                                                                                                                                  ss  xx                                               ",
    "                                                        xx                                                                      o xx                                                               ",
    "                                                                v                                                              xx                                                                  ",
    "                                                           ss                                                                                                                        xxxxxxx       ",
    "                                      v             o xx   xx o                                                                                                                      xx!!!xx       ",
    "                                                  ? o xx   xx o                     xxs oo sxx     ss         ?    ?         o                                oo            oo  o       v         o",
    "                                   xx   xx        o xxxx   xxxx o                   xxxxxxxxxx     xx o       x    x        xx                               xxxx          xxxx x   o      o     ox",
    "                                   xx   xx      o xxxxxx   xxxxxx o                                xxxx o     x  o x      xxxx                               xxxx     o    xxxx x   xx    xx     xx",
    "      @        ssss    o s o       xx o xx      xxxxxxxx   xxxxxxxx         ss      o o o o o o    xxxxxx     x  o x    xxxxxx             ssss            ssxxxx!!!!xxx!!!xxxx x       o        xx",
    "xxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxx  xxx   xxxxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxx          xxxxxxxxxxxx   xxxxxxxxxx!!!!xxx!!!xxxx x xxxxxxxxxx xxxxxx",
    "         x!!!x                                                         x!!!x                                                                       x!!!x                               ",
    "         x!!!x                                                         x!!!x                                                                       xxxxx                               ",
    "         xxxxx                                                         xxxxx                                                                                                           ",
    "                                                                                                                                                                                       ",
    "                                                                                                                                                                                       ",
    "                                                                                                                                                                                       ",
    "                                                                                                                                                                                       ",
    "                                                                                                                                                                                       ",
    "                                                                                                                                                                                       ",
    "                                                                                                               "
  ]
];
